# Generated by Django 5.2.11 on 2026-03-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("center_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("radius_meters", models.PositiveIntegerField()),
                ("place_types", models.JSONField(default=list)),
                ("keyword", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("discovering", "Discovering"),
                            ("enriching_t1", "Enriching (T1)"),
                            ("scoring_t1", "Scoring (T1)"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("businesses_found", models.PositiveIntegerField(default=0)),
                ("businesses_enriched", models.PositiveIntegerField(default=0)),
                ("businesses_scored", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("api_cost_cents", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
