# Generated by Django 5.1.4 on 2026-03-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget_cents', models.PositiveIntegerField(default=0, help_text='Monthly Claude API budget in cents (0 = use env default).')),
                ('max_businesses_per_scan', models.PositiveIntegerField(default=0, help_text='Max businesses per scan (0 = use env default).')),
            ],
            options={
                'verbose_name': 'Site Config',
            },
        ),
    ]
