# Generated by Django 5.1.4 on 2026-03-07 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_add_owner'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='trigger_type',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='scan',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='workspaces.workspace'),
        ),
    ]
