# Generated by Django 5.1.4 on 2026-03-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_description', models.TextField(blank=True)),
                ('target_industries', models.JSONField(default=list)),
                ('target_biz_description', models.TextField(blank=True)),
                ('default_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('default_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('default_radius_meters', models.PositiveIntegerField(default=5000)),
                ('outreach_tone', models.CharField(choices=[('formal', 'Formal & Professional'), ('semi_formal', 'Friendly & Professional'), ('casual', 'Casual & Conversational')], default='semi_formal', max_length=20)),
                ('key_selling_points', models.JSONField(default=list)),
                ('custom_talking_points', models.TextField(blank=True)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('is_configured', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Agent Config',
            },
        ),
    ]
