# Generated by Django 5.1.4 on 2026-03-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cron_expression', models.CharField(help_text="Standard 5-field cron: 'min hour day month weekday'", max_length=100)),
                ('scan_place_types', models.JSONField(default=list, help_text='List of Google Places type strings to search for.')),
                ('scan_keyword', models.CharField(blank=True, max_length=255)),
                ('scan_radius_meters', models.PositiveIntegerField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_name', models.CharField(blank=True, help_text='Name of the linked django-celery-beat PeriodicTask.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Agent Schedule',
                'ordering': ['created_at'],
            },
        ),
    ]
