# Generated by Django 5.2.11 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("tier1", "Tier 1 (Quick)"),
                            ("tier2", "Tier 2 (Full)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("overall_score", models.SmallIntegerField()),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=3)),
                ("crm_score", models.SmallIntegerField()),
                ("scheduling_score", models.SmallIntegerField()),
                ("marketing_score", models.SmallIntegerField()),
                ("invoicing_score", models.SmallIntegerField()),
                ("key_signals", models.JSONField(default=list)),
                ("summary", models.TextField()),
                ("recommended_pitch_angle", models.TextField(blank=True)),
                (
                    "estimated_deal_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_dossier", models.TextField(blank=True)),
                ("competitor_analysis", models.TextField(blank=True)),
                ("model_used", models.CharField(max_length=100)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("api_cost_cents", models.PositiveIntegerField(default=0)),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-overall_score"],
                "indexes": [
                    models.Index(
                        fields=["-overall_score"], name="scoring_aut_overall_f8b6f3_idx"
                    ),
                    models.Index(fields=["tier"], name="scoring_aut_tier_14aa4c_idx"),
                ],
            },
        ),
    ]
