# Generated by Django 5.2.11 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("website_reachable", models.BooleanField(blank=True, null=True)),
                ("website_title", models.CharField(blank=True, max_length=512)),
                ("website_description", models.TextField(blank=True)),
                ("website_text_content", models.TextField(blank=True)),
                (
                    "website_load_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("has_ssl", models.BooleanField(blank=True, null=True)),
                ("is_mobile_responsive", models.BooleanField(blank=True, null=True)),
                ("website_platform", models.CharField(blank=True, max_length=100)),
                ("detected_technologies", models.JSONField(default=list)),
                ("has_online_booking", models.BooleanField(blank=True, null=True)),
                ("has_live_chat", models.BooleanField(blank=True, null=True)),
                ("has_contact_form", models.BooleanField(blank=True, null=True)),
                ("has_email_signup", models.BooleanField(blank=True, null=True)),
                ("detected_crm", models.CharField(blank=True, max_length=200)),
                (
                    "detected_scheduling_tool",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "detected_email_platform",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "detected_payment_processor",
                    models.CharField(blank=True, max_length=200),
                ),
                ("detected_analytics", models.JSONField(default=list)),
                ("social_links", models.JSONField(default=dict)),
                ("facebook_url", models.URLField(blank=True, max_length=1024)),
                ("instagram_url", models.URLField(blank=True, max_length=1024)),
                ("linkedin_url", models.URLField(blank=True, max_length=1024)),
                ("yelp_url", models.URLField(blank=True, max_length=1024)),
                ("review_summary", models.TextField(blank=True)),
                ("negative_signals", models.JSONField(default=list)),
                ("positive_signals", models.JSONField(default=list)),
                ("enriched_at", models.DateTimeField(blank=True, null=True)),
                ("error_log", models.TextField(blank=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment",
                        to="businesses.business",
                    ),
                ),
            ],
        ),
    ]
