# Generated by Django 5.1.4 on 2026-03-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrichmentprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
