# Generated by Django 5.2.11 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outreach_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("researching", "Researching"),
                            ("outreach_ready", "Outreach Ready"),
                            ("contacted", "Contacted"),
                            ("follow_up", "Follow Up"),
                            ("responded", "Responded"),
                            ("meeting_booked", "Meeting Booked"),
                            ("proposal_sent", "Proposal Sent"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("not_interested", "Not Interested"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("generated_email", models.TextField(blank=True)),
                (
                    "generated_email_subject",
                    models.CharField(blank=True, max_length=255),
                ),
                ("generated_call_script", models.TextField(blank=True)),
                ("outreach_generated_at", models.DateTimeField(blank=True, null=True)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("next_followup_at", models.DateTimeField(blank=True, null=True)),
                ("contact_attempts", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead",
                        to="businesses.business",
                    ),
                ),
                (
                    "lists",
                    models.ManyToManyField(
                        blank=True, related_name="leads", to="leads.leadlist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("note_added", "Note Added"),
                            ("email_generated", "Email Generated"),
                            ("call_script_generated", "Call Script Generated"),
                            ("contacted", "Contacted"),
                            ("tag_added", "Tag Added"),
                            ("tier2_requested", "Tier 2 Requested"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
