# Generated by Django 5.2.11 on 2026-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="leadactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status Change"),
                    ("note_added", "Note Added"),
                    ("email_generated", "Email Generated"),
                    ("call_script_generated", "Call Script Generated"),
                    ("contacted", "Contacted"),
                    ("tag_added", "Tag Added"),
                    ("tier2_requested", "Tier 2 Requested"),
                    ("email_sent", "Email Sent"),
                ],
                max_length=30,
            ),
        ),
    ]
