# Generated by Django 5.1.4 on 2026-03-07 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_workspace_leadlist_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('note_added', 'Note Added'), ('email_generated', 'Email Generated'), ('call_script_generated', 'Call Script Generated'), ('contacted', 'Contacted'), ('tag_added', 'Tag Added'), ('tier2_requested', 'Tier 2 Requested'), ('email_sent', 'Email Sent'), ('outreach_approved', 'Outreach Approved'), ('outreach_rejected', 'Outreach Rejected')], max_length=30),
        ),
    ]
