# Generated by Django 5.2.11 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                ("google_maps_url", models.URLField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=512)),
                ("formatted_address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("website_url", models.URLField(blank=True, max_length=1024)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("place_types", models.JSONField(default=list)),
                ("business_status", models.CharField(blank=True, max_length=50)),
                ("price_level", models.SmallIntegerField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("opening_hours", models.JSONField(default=dict)),
                ("reviews_data", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to="scans.scan",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="businesses__latitud_6c4c1d_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="businesses__rating_797df6_idx"
                    ),
                ],
            },
        ),
    ]
