# Generated by Django 5.1.4 on 2026-03-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tier2_pending',
            field=models.BooleanField(default=False),
        ),
    ]
